apiVersion: v1
kind: Service
metadata:
  name: api-server
  namespace: kube-system
spec:
  ports:
  - name: ssl
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    component: cilium-api
  type: ClusterIP
